apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-service-account
  namespace: default
secrets:
  - name: image-registry-credentials
imagePullSecrets:
  - name: image-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/spring-boot
  - image: gcr.io/paketo-buildpacks/java
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder
spec:
  serviceAccount: builder-service-account
  tag: th3n3rd/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/spring-boot
    - id: paketo-buildpacks/java
